# Generated by Django 3.2.7 on 2021-10-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='photos/')),
                ('Image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoslog.category')),
                ('Image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoslog.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
