# Generated by Django 3.2.7 on 2021-10-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoslog', '0003_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
